###
GET http://localhost:3000/api/articles/
Accept: application/json
### Получить статьи

GET http://localhost:3000/api/articles/59YknF
Accept: application/json
### Получить статью с айди 59YknF

POST http://localhost:3000/api/articles/
Content-Type: application/json

{
  "title": "Новая публикация Тест",
  "description": "Тест тест тест",
  "announce": "Текст анонса",
  "fullText": "Полный текст",
  "category": ["Жизнь"]
}
### Добавить статью

PUT http://localhost:3000/api/articles/59YknF
Content-Type: application/json

{
  "title": "Отредактированная публикация"
}
### Отредактировать статью

DELETE http://localhost:3000/api/articles/59YknF
Content-Type: application/json
### Удалить статью


GET http://localhost:3000/api/articles/4KqzOI/comments/
Accept: application/json
### Получить комментарии к статье с айди 4KqzOI


POST http://localhost:3000/api/articles/4KqzOI/comments/
Content-Type: application/json

{
  "author": "Тест Тест",
  "text": "Тестовый комментарий"
}
### Добавить комментарий к статье с айди n1engc

DELETE http://localhost:3000/api/articles/4KqzOI/comments/EkpK5L
Accept: application/json
### Удалить комментарии к статье с айди n1engc
